"""Prepare uniformly framed gallery images from the final annotations.

Each overlay is cropped around its annotated object with generous context, padded
with solid white where necessary, and resized isotropically to a fixed square.
The operation never stretches, redraws, or independently moves keypoints.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
import json
import math
from pathlib import Path
import re

from PIL import Image, ImageColor


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--images", required=True, type=Path)
    parser.add_argument("--annotations", required=True, type=Path)
    parser.add_argument("--site-data", default=Path("data/site-data.js"), type=Path)
    parser.add_argument("--target-size", default=256, type=int)
    parser.add_argument("--context-scale", default=1.25, type=float)
    parser.add_argument("--background", default="#ffffff")
    return parser.parse_args()


def read_site_data(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    return json.loads(text[text.index("=") + 1 : text.rindex(";")])


def write_site_data(path: Path, data: dict) -> None:
    banner = "/* Auto-generated by scripts/build_site_data.mjs; gallery crops prepared by scripts/prepare_gallery_images.py. */\n"
    path.write_text(
        banner
        + "window.POSEIMAGENET_DATA = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )


def normalize(value: object) -> str:
    return " ".join(str(value).split()).casefold()


def prototype_id_from_src(src: str) -> int:
    match = re.search(r"-(\d+)-\d+\.(?:png|jpe?g)$", Path(src).name, re.IGNORECASE)
    if not match:
        raise ValueError(f"Cannot parse prototype/category id from {src}")
    return int(match.group(1))


def annotation_extent(
    annotation: dict, scale_x: float, scale_y: float
) -> tuple[float, float, float, float]:
    x, y, width, height = map(float, annotation["bbox"])
    xs = [x * scale_x, (x + width) * scale_x]
    ys = [y * scale_y, (y + height) * scale_y]

    keypoints = annotation.get("keypoints", [])
    for index in range(0, len(keypoints), 3):
        keypoint_x, keypoint_y, visibility = keypoints[index : index + 3]
        if float(visibility) > 0:
            xs.append(float(keypoint_x) * scale_x)
            ys.append(float(keypoint_y) * scale_y)

    return min(xs), min(ys), max(xs), max(ys)


def square_crop(
    image: Image.Image,
    extent: tuple[float, float, float, float],
    context_scale: float,
    target_size: int,
    background: tuple[int, int, int],
) -> tuple[Image.Image, tuple[float, float, float, float], float]:
    x_min, y_min, x_max, y_max = extent
    extent_width = x_max - x_min
    extent_height = y_max - y_min
    max_extent = max(extent_width, extent_height)
    if max_extent <= 0:
        raise ValueError(f"Invalid annotation extent: {extent}")

    side = max(1.0, max_extent * context_scale)
    center_x = (x_min + x_max) / 2
    center_y = (y_min + y_max) / 2
    left = center_x - side / 2
    top = center_y - side / 2
    right = left + side
    bottom = top + side

    source_units_per_pixel = side / target_size
    canvas = image.transform(
        (target_size, target_size),
        Image.Transform.AFFINE,
        (
            source_units_per_pixel,
            0,
            left,
            0,
            source_units_per_pixel,
            top,
        ),
        resample=Image.Resampling.BICUBIC,
        fillcolor=background,
    )

    minimum_safety = (side - max_extent) / 2 - 1.5
    edge_distances = (
        x_min - left,
        y_min - top,
        right - x_max,
        bottom - y_max,
    )
    if min(edge_distances) < minimum_safety:
        raise RuntimeError(
            "Annotation lost its configured safety margin: "
            f"extent={extent}, crop={(left, top, right, bottom)}"
        )

    return canvas, (left, top, right, bottom), max_extent / side


def main() -> None:
    args = parse_args()
    if args.target_size <= 0:
        raise ValueError("--target-size must be positive")
    if args.context_scale < 1:
        raise ValueError("--context-scale must be at least 1")

    data = read_site_data(args.site_data)
    annotations_data = json.loads(args.annotations.read_text(encoding="utf-8"))
    source_dirs = {
        normalize(entry.name): entry
        for entry in args.images.iterdir()
        if entry.is_dir()
    }

    images_by_class_and_stem: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for image_record in annotations_data["images"]:
        key = (
            normalize(image_record.get("category", "")),
            normalize(Path(image_record["file_name"]).stem),
        )
        images_by_class_and_stem[key].append(image_record)

    annotations_by_image_and_category: dict[tuple[int, int], list[dict]] = defaultdict(list)
    for annotation in annotations_data["annotations"]:
        annotations_by_image_and_category[
            (int(annotation["image_id"]), int(annotation["category_id"]))
        ].append(annotation)

    background = ImageColor.getrgb(args.background)
    results = []
    legacy_outputs: set[Path] = set()
    for row in data["gallery"]:
        semantic_key = normalize(row["semanticClass"])
        source_dir = source_dirs.get(semantic_key)
        if source_dir is None:
            raise FileNotFoundError(f"No image directory for semantic class {row['semanticClass']}")

        for sample in row["samples"]:
            source = source_dir / f"{sample['id']}_2_pose_overlay.jpg"
            if not source.exists():
                raise FileNotFoundError(source)

            category_id = prototype_id_from_src(sample["src"])
            candidate_images = images_by_class_and_stem.get(
                (semantic_key, normalize(sample["id"])), []
            )
            matches = []
            for image_record in candidate_images:
                matching_annotations = annotations_by_image_and_category.get(
                    (int(image_record["id"]), category_id), []
                )
                matches.extend(
                    (image_record, annotation) for annotation in matching_annotations
                )
            if len(matches) != 1:
                raise RuntimeError(
                    f"Expected one JSON match for {row['semanticClass']}/{sample['id']} "
                    f"and category {category_id}, got {len(matches)}"
                )

            image_record, annotation = matches[0]
            original = Image.open(source).convert("RGB")
            json_width = int(image_record["width"])
            json_height = int(image_record["height"])
            if json_width <= 0 or json_height <= 0:
                raise ValueError(f"Invalid JSON image dimensions for {sample['id']}")

            scale_x = original.width / json_width
            scale_y = original.height / json_height
            extent = annotation_extent(annotation, scale_x, scale_y)
            resized, crop_box, occupancy = square_crop(
                original,
                extent,
                args.context_scale,
                args.target_size,
                background,
            )
            crop_side = crop_box[2] - crop_box[0]

            old_output = Path(sample["src"])
            output = old_output.with_suffix(".png")
            legacy_outputs.add(output.with_suffix(".jpg"))
            output.parent.mkdir(parents=True, exist_ok=True)
            resized.save(output, "PNG", optimize=True)

            with Image.open(output) as saved:
                if saved.size != (args.target_size, args.target_size):
                    raise RuntimeError(
                        f"Unexpected output size for {sample['id']}: {saved.size}"
                    )

            output_scale_x = args.target_size / crop_side
            output_scale_y = args.target_size / crop_side
            if not math.isclose(
                output_scale_x, output_scale_y, rel_tol=0, abs_tol=1e-12
            ):
                raise RuntimeError(f"Anisotropic output scale for {sample['id']}")

            x_min, y_min, x_max, y_max = extent
            left, top, _, _ = crop_box
            content_box = (
                (x_min - left) * output_scale_x,
                (y_min - top) * output_scale_y,
                (x_max - left) * output_scale_x,
                (y_max - top) * output_scale_y,
            )
            content_center = (
                (content_box[0] + content_box[2]) / 2,
                (content_box[1] + content_box[3]) / 2,
            )
            expected_center = args.target_size / 2
            if max(abs(value - expected_center) for value in content_center) > 1e-6:
                raise RuntimeError(
                    f"Content alignment failed for {sample['id']}: {content_center}"
                )

            sample["src"] = output.as_posix()
            results.append(
                {
                    "id": sample["id"],
                    "source": f"{original.width}x{original.height}",
                    "crop": list(crop_box),
                    "cropSide": crop_side,
                    "output": f"{args.target_size}x{args.target_size}",
                    "objectOccupancy": round(occupancy, 4),
                    "isotropicScale": round(output_scale_x, 6),
                    "contentBox": [round(value, 2) for value in content_box],
                    "contentCenter": [round(value, 2) for value in content_center],
                }
            )

    if len(results) != 78:
        raise RuntimeError(f"Expected 78 images, got {len(results)}")

    data.setdefault("meta", {})["galleryVersion"] = (
        f"{args.target_size}px-{args.context_scale:g}-aligned-v1"
    )
    write_site_data(args.site_data, data)
    removed_legacy_jpgs = 0
    for legacy_output in legacy_outputs:
        if legacy_output.exists():
            legacy_output.unlink()
            removed_legacy_jpgs += 1

    print(
        json.dumps(
            {
                "processed": len(results),
                "outputSize": f"{args.target_size}x{args.target_size}",
                "contextScale": args.context_scale,
                "allAnnotationsInsideSafetyMargin": True,
                "allOutputScalesIsotropic": True,
                "allContentCentersAligned": True,
                "objectOccupancyRange": [
                    min(item["objectOccupancy"] for item in results),
                    max(item["objectOccupancy"] for item in results),
                ],
                "cropSideRange": [
                    min(item["cropSide"] for item in results),
                    max(item["cropSide"] for item in results),
                ],
                "removedLegacyJpgs": removed_legacy_jpgs,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
